### ISSUE TITLE
There are wired `<feff>` character in income.csv

### ISSUE THREAD

**Issue by humorless** [g0v/tw_campaign_finance#6]
Using this command
`curl -o data/incomes.csv https://lydata.ronny-s3.click/incomes.csv`

Then, I run `dbt run`, and it says something wrong.

> Runtime Error in model campaign_transaction (models/campaign_transaction.sql)
> Binder Error: Referenced column "序號" not found in FROM clause!
>  Candidate bindings: "raw_transaction.﻿序號"
>   LINE 25: "序號" as seq,

<img width="563" alt="截圖 2023-07-27 下午11 02 21" src="https://github.com/g0v/tw_campaign_finance/assets/3061798/3c3638d0-8870-4580-8ec1-88187c0789f9">

It turns out that there is a wried `<feff>` character in `income.csv` and `expenditures.csv`

**Comment by clkao** [comment]
appeared to be resolved per https://g0v-tw.slack.com/archives/CH79PR9FY/p1690796582008519
